spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/englishByHeart
        username: myuser
        password: secret
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true
        hibernate:
            ddl-auto: create
    session:
        jdbc:
            initialize-schema: always
            table-name: SPRING_SESSION
    freemarker:
        expose-request-attributes: true
        expose-session-attributes: true
        suffix: .ftl
upload:
    path: /home/kklimkov/Desktop/EnglishByHeart/pictures

springdoc:
    api-docs:
        path: /api-docs
